# Generated by Django 4.1.4 on 2023-01-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complementos', '0003_instalaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalaciones',
            old_name='imgins',
            new_name='image',
        ),
    ]
