# Generated by Django 4.1.4 on 2023-02-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complementos', '0006_oferta_description_alter_oferta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
