# Generated by Django 4.1.4 on 2023-02-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complementos', '0009_alter_oferta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
    ]
