# Generated by Django 4.1.4 on 2023-01-25 16:31

import applications.clientes.models
import applications.clientes.validators
import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[applications.clientes.validators.text_validation], verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(max_length=9, unique=True, validators=[applications.clientes.validators.phone_validation], verbose_name='Numero')),
                ('message', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Titulo')),
                ('response', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Respuesta')),
                ('read', models.BooleanField(default=False, verbose_name='Respondido')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Sonrisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client', models.CharField(max_length=30, unique=True, verbose_name='Cliente')),
                ('image', models.ImageField(blank=True, null=True, upload_to=applications.clientes.models.wrapper, verbose_name='Foto')),
                ('beforeimage', models.ImageField(upload_to=applications.clientes.models.wrapper2, verbose_name='Antes')),
                ('afterimage', models.ImageField(upload_to=applications.clientes.models.wrapper3, verbose_name='Después')),
                ('comment', models.TextField(max_length=500, verbose_name='Comentario')),
                ('date', models.DateField(default=datetime.date.today)),
                ('public', models.BooleanField(default=False, verbose_name='Pestaña Antes y después')),
                ('inicio', models.BooleanField(default=False, verbose_name='Pestaña Inicio')),
            ],
            options={
                'verbose_name': 'Sonrisa',
                'verbose_name_plural': 'Sonrisas',
                'ordering': ['client'],
            },
        ),
    ]
