# Generated by Django 4.1.4 on 2023-01-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonrisa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Home/', verbose_name='Foto'),
        ),
    ]
