# Generated by Django 4.1.4 on 2023-01-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_sonrisa_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonrisa',
            name='afterimage',
            field=models.ImageField(upload_to='Home', verbose_name='Después'),
        ),
        migrations.AlterField(
            model_name='sonrisa',
            name='beforeimage',
            field=models.ImageField(upload_to='Home/', verbose_name='Antes'),
        ),
    ]
