# Generated by Django 4.1.4 on 2023-01-31 22:56

import applications.clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_sonrisa_afterimage_alter_sonrisa_beforeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonrisa',
            name='afterimage',
            field=models.ImageField(upload_to=applications.clientes.models.wrapper3, verbose_name='Después'),
        ),
        migrations.AlterField(
            model_name='sonrisa',
            name='beforeimage',
            field=models.ImageField(upload_to=applications.clientes.models.wrapper2, verbose_name='Antes'),
        ),
        migrations.AlterField(
            model_name='sonrisa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=applications.clientes.models.wrapper, verbose_name='Foto'),
        ),
    ]
