# Generated by Django 4.1.4 on 2023-02-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_sonrisa_afterimage_alter_sonrisa_beforeimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='tipo',
            field=models.BooleanField(default=False, verbose_name='oferta'),
        ),
    ]
