# Generated by Django 4.1.4 on 2023-02-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_formulario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='tipo',
        ),
    ]
