# Generated by Django 4.1.4 on 2023-01-25 16:31

import applications.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pcontanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsp', models.BooleanField(default=False, verbose_name='whatsApp')),
                ('email', models.BooleanField(default=False, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'P. Contanto',
                'verbose_name_plural': 'P. Contacto',
            },
        ),
        migrations.CreateModel(
            name='Ptecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False, verbose_name='Visible')),
                ('tecnologias', models.ManyToManyField(blank=True, to='empresa.tecnologia')),
            ],
            options={
                'verbose_name': 'P.Tecnologías',
                'verbose_name_plural': 'P. Tecnologías',
            },
        ),
        migrations.CreateModel(
            name='Pservicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False, verbose_name='Visible')),
                ('servicios', models.ManyToManyField(blank=True, to='empresa.servicio')),
            ],
            options={
                'verbose_name': 'P. Servicios',
                'verbose_name_plural': 'P. Servicios',
            },
        ),
        migrations.CreateModel(
            name='PInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Titulo')),
                ('sub_title', models.CharField(max_length=50, verbose_name='Frase')),
                ('image', models.ImageField(upload_to=applications.home.models.PInicio.wrapper, verbose_name='Imágen')),
                ('logo', models.ImageField(upload_to=applications.home.models.PInicio.wrapper, verbose_name='Logo')),
                ('bdescription', models.TextField(max_length=150, verbose_name='Descripción Breve')),
                ('Mision', models.TextField(blank=True, max_length=200, null=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, max_length=200, null=True, verbose_name='Visión')),
                ('empleados', models.ManyToManyField(blank=True, to='empresa.empleado')),
                ('servicios', models.ManyToManyField(blank=True, to='empresa.servicio')),
            ],
            options={
                'verbose_name': 'P. Inicio',
                'verbose_name_plural': 'P. Inicio',
            },
        ),
        migrations.CreateModel(
            name='PhorarioUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False, verbose_name='Horarios Visible')),
                ('info', models.BooleanField(default=False, verbose_name='Ubicación Visible')),
                ('horarios', models.ManyToManyField(blank=True, to='empresa.horario')),
            ],
            options={
                'verbose_name': 'P. Horario y Ubicación',
                'verbose_name_plural': 'P. Horarios y Ubicación',
            },
        ),
        migrations.CreateModel(
            name='Pclinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to=applications.home.models.Pclinica.wrapper, verbose_name='Imágen')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción extensa')),
                ('public', models.BooleanField(default=False, verbose_name='Visible')),
                ('empleados', models.ManyToManyField(blank=True, to='empresa.empleado')),
            ],
            options={
                'verbose_name': 'P. Clinica',
                'verbose_name_plural': 'P. Clinica',
            },
        ),
        migrations.CreateModel(
            name='PantesDespues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False, verbose_name='Visible')),
                ('sonrisas', models.ManyToManyField(blank=True, to='clientes.sonrisa')),
            ],
            options={
                'verbose_name': 'P. Antes y Después',
                'verbose_name_plural': 'P. Antes y Después',
            },
        ),
    ]
