# Generated by Django 4.1.4 on 2023-01-25 20:15

import applications.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pclinica',
            name='insfirsttmg',
            field=models.ImageField(default='', upload_to=applications.home.models.Pclinica.wrapper, verbose_name='Imágen Instalación 1'),
        ),
        migrations.AddField(
            model_name='pclinica',
            name='inssectmg',
            field=models.ImageField(default='', upload_to=applications.home.models.Pclinica.wrapper, verbose_name='Imágen Instalación 2'),
        ),
    ]
