# Generated by Django 4.1.4 on 2023-01-25 20:16

import applications.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pclinica_insfirsttmg_pclinica_inssectmg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pclinica',
            name='insfirsttmg',
            field=models.ImageField(blank=True, upload_to=applications.home.models.Pclinica.wrapper, verbose_name='Imágen Instalación 1'),
        ),
        migrations.AlterField(
            model_name='pclinica',
            name='inssectmg',
            field=models.ImageField(blank=True, upload_to=applications.home.models.Pclinica.wrapper, verbose_name='Imágen Instalación 2'),
        ),
    ]
