# Generated by Django 4.1.4 on 2023-01-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('home', '0003_alter_pclinica_insfirsttmg_alter_pclinica_inssectmg'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinicio',
            name='comentarios',
            field=models.ManyToManyField(blank=True, to='clientes.sonrisa'),
        ),
    ]
