# Generated by Django 4.1.4 on 2023-01-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complementos', '0003_instalaciones'),
        ('home', '0004_pinicio_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pclinica',
            name='insfirsttmg',
        ),
        migrations.RemoveField(
            model_name='pclinica',
            name='inssectmg',
        ),
        migrations.AddField(
            model_name='pclinica',
            name='instalaciones',
            field=models.ManyToManyField(blank=True, to='complementos.instalaciones'),
        ),
    ]
