# Generated by Django 4.1.4 on 2023-01-25 16:31

import applications.empresa.models
import applications.empresa.validators
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complementos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tls', models.BooleanField(default=True, verbose_name='EMAIL_USE_TLS')),
                ('emailhost', models.CharField(default='smtp.gmail.com', max_length=1024, verbose_name='EMAIL_HOST')),
                ('email', models.EmailField(max_length=255, verbose_name='EMAIL_USER')),
                ('password', models.CharField(max_length=255, verbose_name='EMAIL_PASS')),
                ('emailport', models.PositiveSmallIntegerField(default=587, verbose_name='EMAIL_PORT')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the', models.CharField(choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miercoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sábado'), ('6', 'Domingo')], max_length=11, verbose_name='De')),
                ('to', models.CharField(blank=True, choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miercoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sábado'), ('6', 'Domingo')], max_length=11, verbose_name='a')),
                ('of', models.TimeField(verbose_name='Desde')),
                ('until', models.TimeField(verbose_name='Hasta')),
                ('public', models.BooleanField(default=False, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción')),
                ('image', models.ImageField(default='', upload_to=applications.empresa.models.wrapper, verbose_name='Imágen')),
                ('hash', models.CharField(editable=False, max_length=20)),
                ('public', models.BooleanField(default=False, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(default='', upload_to=applications.empresa.models.wrapper, verbose_name='Imagen')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('public', models.BooleanField(default=False, verbose_name='Pestaña servicio')),
                ('inicio', models.BooleanField(default=False, verbose_name='Pestaña Inicio')),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_cate', to='complementos.categoria')),
                ('etiquetas', models.ManyToManyField(to='complementos.tag')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60, verbose_name='Direccion')),
                ('district', models.CharField(max_length=200, verbose_name='Distrito')),
                ('phome', models.CharField(max_length=9, unique=True, validators=[applications.empresa.validators.phone_validation], verbose_name='Numero')),
                ('house', models.CharField(max_length=10, unique=True, validators=[applications.empresa.validators.house_validation], verbose_name='Numero Fijo')),
                ('gmail', models.EmailField(max_length=254, verbose_name='Correo')),
                ('redes', models.ManyToManyField(to='complementos.redes')),
            ],
            options={
                'verbose_name': 'Información',
                'verbose_name_plural': 'Información',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('image', models.ImageField(upload_to=applications.empresa.models.wrapper, verbose_name='Foto Perfil')),
                ('public', models.BooleanField(default=False, verbose_name='Pestaña Clinica')),
                ('inicio', models.BooleanField(default=False, verbose_name='Pestaña Inicio')),
                ('especialidad', models.ManyToManyField(to='complementos.especialidad')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['name'],
                'unique_together': {('name', 'last_name')},
            },
        ),
    ]
