# Generated by Django 4.1.4 on 2023-01-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='especialidad',
            new_name='categoria',
        ),
    ]
