# Generated by Django 4.1.4 on 2023-01-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_empleado_cop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='inicio',
        ),
    ]
