# Generated by Django 4.1.4 on 2023-01-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_remove_servicio_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
    ]
