# Generated by Django 4.1.4 on 2023-02-02 03:48

import applications.empresa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_servicio_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='image',
            field=models.ImageField(upload_to=applications.empresa.models.wrapper3, verbose_name='Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='image',
            field=models.ImageField(default='', upload_to=applications.empresa.models.wrapper2, verbose_name='Imagen'),
        ),
    ]
